SEED: 42
TRAIN_SIZE: 0.8
DEVICE: cpu  # options: 'cpu' or 'cuda'
DATA_PATH: data
OBJECT_NAME: ketchup_heinz_400ml_1200_4096_segmentation_40960_1200.h5
MODELS_PATH: models/architectures
USE_COLORS: true
TRAIN:
  EXPERIMENT_NAME: exp_2
  BATCH_SIZE: 4
  LR: 0.001
  WEIGHT_DECAY: 0.0001
  EPOCHS: 100
  NUM_WORKERS: 0
  SHUFFLE: true
  PIN_MEMORY: true
  DROP_LAST: true
  NORMALIZE: true
  CONTINUE_FROM_EPOCH: -1 # Resume from epoch (-1: from scratch, -2: last checkpoint, int: specific epoch)
MODEL:
  NAME: pointnet # name of script without ".py" at directory specified in MODELS_PATH
  NUM_CLASSES: 2
  INPUT_DIM: 3
  OUTPUT_DIM: 2
  EMBEDDING_DIM: 512
  NUM_LAYERS: 4
  DROPOUT: 0.5
  BATCH_NORM: true
DATA: # Parameters for data processing
  WITH_REAL_BACKGROUND: True # CHANGE TO TAKE BACKGROUND FROM REAL SCENES IN THE TEST SET
  NUM_POINTS_PER_OBJECT: 2048 # number of points per object
  MAX_NUM_OBJECTS: 10 # max number of objects in per point cloud sample (1 target and NUM_OBJECTS - 1 alien objects)
  RAW_DATASET_DIR: D:\Datasets\MinimarketPointCloud\MiniMarket_raw  # Path to the main raw (unprocessed) dataset folder. Each subfolder represents a different object and contains its corresponding .pcd point cloud files.
  POINTCLOUD_SAVE_DIR: D:\Datasets\MinimarketPointCloud\MiniMarket_point_clouds # Path to save processed point clouds in .h5 format and with the number of points specified in NUM_POINTS_PER_OBJECT
  TARGET_OBJECT_NAME: ketchup_heinz_400ml # Name of the object to segment out of the raw dataset. The script will assign point of TARGET_OBJECT_NAME to make the target class mask and all other points to the alien class mask.
  NUM_ORIENTATIONS: 10 # Number of orientations to generate for each object. The script will generate NUM_ORIENTATIONS copies of each object with different orientations.
  NUM_PRODUCTS_IN_DATASET: 82 # NOT LIKELY TO CHANGE! Number of products in the dataset. The script will generate point clouds for all products in the dataset.
  RAW_TEST_SET_DIR: D:\Datasets\MinimarketPointCloud\MiniMarket_point_clouds\test\all_test_scenes.h5
  NUM_SCENES: 1200