SEED: 42
TRAIN_SIZE: 0.8
DEVICE: cpu  # options: 'cpu' or 'cuda'
DATA_PATH: data
OBJECT_NAME: ketchup_heinz_400ml_1200_4096_segmentation_40960_1200.h5
NUM_POINTS_PER_SEG_SAMPLE: 40960  # 4096 points per object x 10 objects per sample
MODELS_PATH: models
TRAIN:
  BATCH_SIZE: 32
  LR: 0.001
  WEIGHT_DECAY: 0.0001
  EPOCHS: 100
  NUM_WORKERS: 4
  SHUFFLE: true
  PIN_MEMORY: true
  DROP_LAST: true
MODEL:
  NAME: pointnet2
  NUM_CLASSES: 2
  INPUT_DIM: 3
  OUTPUT_DIM: 2
  EMBEDDING_DIM: 512
  NUM_LAYERS: 4
  DROPOUT: 0.5
  BATCH_NORM: true

